"""M0-sourced anchor seam (Amendment 4 / R19, user ruling 2026-08-04 ~13:50).

Config seam `"anchor_source": "m0"` in configs/lines/<line>.json: the
model-generated anchor-TARGET sets of the four shared trainers (benign-KL
GSM8K trace targets + helpfulness/near-boundary CE targets, Amendment 3d)
are generated by the LINE M0 (L["hf_id"]) — greedy, think-off, identical
pre-registered prompt sets and budgets — instead of the stage source
(seed trainers already generate from clean M0, so the seam is a target
no-op there; the DPO rung trainers switch from CLEAN --src to M0).
Refusal pins stay src-sourced (out of R19 scope: the pin is the defended
model's OWN refusals). Absent key = legacy behavior, byte-identical.

Evidence basis (27B fleet forensics 2026-08-04 ~12:35, tracker): fleet
re-seed GSM8K drop 5.6pts (McNemar p=1.75e-04) with SEED-sourced anchors
already in the KL set — anchor SOURCE, not anchor presence, is the lever;
verbosity chain M0 638 -> seed 978 -> r1 1140 median output tokens.

This module carries the VERBOSITY GUARD readout: median output tokens on
the GSM8K anchor set, stage source vs M0, at the anchor generation budget.
Log-only tripwire (VERBOSITY_FLAG marker at ratio > 1.25) — the enforced
gates remain the in-chain GSM8K n=100 gate and the registered n=500
kill-switch. Content hygiene: counts/ratios only, never generation text.
"""
import hashlib
import json
from pathlib import Path
from statistics import median

FLAG_RATIO = 1.25

# pre-computed M0 anchor-trace artifacts (scripts/line_anchor_traces.py):
# one JSON per line under data/train/anchors_m0/, provenance-pinned so a
# trainer can NEVER consume traces from the wrong model/prompt-set/budget.
# Budgets are the registered anchor budgets (R19: identical to the legacy
# pre-LoRA pass — gsm 256 tok / batch 12, near-boundary 128 tok / batch 12).
TRACES_SUBDIR = "data/train/anchors_m0"
GSM_BUDGET = [256, 12]
NB_BUDGET = [128, 12]


def prompts_sha(prompts):
    return hashlib.sha256("\n".join(prompts).encode()).hexdigest()


def traces_path(root, line):
    return Path(root) / TRACES_SUBDIR / f"{line}.json"


def load_m0_traces(root, L, gsm_q, nb_prompts=None):
    """Load the pre-computed M0 anchor traces for this line, or None.

    Returns (gsm_targets, nb_targets, path) iff the artifact exists AND its
    provenance matches: m0_model == L["hf_id"], chat_kwargs equal, prompt-set
    sha256 equal (gsm always; nb too when nb_prompts is given), budgets equal
    the registered ones. Any mismatch -> None (caller generates in-process;
    a mismatched artifact must never be silently consumed)."""
    p = traces_path(root, L["line"])
    if not p.is_file():
        return None
    try:
        art = json.load(open(p))
    except Exception:
        return None
    prov = art.get("provenance", {})
    if (prov.get("m0_model") != L["hf_id"]
            or prov.get("chat_kwargs") != L.get("chat_kwargs", {})
            or prov.get("gsm_prompts_sha256") != prompts_sha(gsm_q)
            or prov.get("gsm_budget") != GSM_BUDGET
            or len(art.get("gsm_targets", [])) != len(gsm_q)):
        return None
    nb_targets = None
    if nb_prompts is not None:
        if (prov.get("nb_prompts_sha256") != prompts_sha(nb_prompts)
                or prov.get("nb_budget") != NB_BUDGET
                or len(art.get("nb_targets", [])) != len(nb_prompts)):
            return None
        nb_targets = art["nb_targets"]
    return art["gsm_targets"], nb_targets, p


def gsm_verbosity_guard(tok, src_outs, m0_outs, cap, art_path, extra=None):
    """Median-output-token verbosity readout on the GSM8K anchor set.

    tok       tokenizer of the generating adapter (token counts only)
    src_outs  the STAGE SOURCE's greedy outputs on the anchor prompts
              (seed stage: source IS M0 -> ratio 1.00 books the reference)
    m0_outs   the M0-generated anchor targets on the same prompts
    cap       the anchor generation budget (at-cap counts logged both sides)
    art_path  artifact JSON destination (counts/medians/ratio only)
    extra     provenance keys (line/stage/trainer/models) merged into the
              artifact — never text

    Prints the registered [verbosity-guard] line (+ VERBOSITY_FLAG marker at
    ratio > FLAG_RATIO), persists the stats, returns them.
    """
    def _toks(outs):
        return [len(tok(o or "", add_special_tokens=False).input_ids)
                for o in outs]
    t_src, t_m0 = _toks(src_outs), _toks(m0_outs)
    med_src, med_m0 = median(t_src), median(t_m0)
    ratio = med_src / max(med_m0, 1)
    stats = {"n": len(src_outs), "cap_tokens": cap,
             "median_src": med_src, "median_m0": med_m0,
             "ratio": round(ratio, 4),
             "at_cap_src": sum(t >= cap for t in t_src),
             "at_cap_m0": sum(t >= cap for t in t_m0),
             "flag_ratio": FLAG_RATIO, "flag": ratio > FLAG_RATIO,
             "saturated": med_m0 >= cap,
             **(extra or {})}
    print(f"[verbosity-guard] gsm anchors n={stats['n']}: "
          f"median_src={med_src} median_m0={med_m0} ratio={ratio:.3f} "
          f"at_cap src={stats['at_cap_src']}/m0={stats['at_cap_m0']} "
          f"(cap {cap})", flush=True)
    if stats["saturated"]:
        # Qwen3.5-class M0s already hit the 256-token anchor cap on GSM8K
        # (9B reference: at_cap 73/100) — a capped median can never show a
        # >1.25x ratio, so say so loudly instead of logging a vacuous 1.00
        print(f"[verbosity-guard] SATURATED: M0 median sits at the anchor "
              f"cap ({cap}) — the ratio is uninformative here; read the "
              f"at_cap counts (src {stats['at_cap_src']}/{stats['n']} vs m0 "
              f"{stats['at_cap_m0']}/{stats['n']}) and rely on the GSM8K "
              f"eval gate", flush=True)
    if stats["flag"]:
        print(f"VERBOSITY_FLAG: stage source median output tokens "
              f"{ratio:.2f}x M0 on the GSM8K anchor set (> {FLAG_RATIO}) — "
              f"Amendment 4 tripwire (log-only; the GSM8K eval gate is the "
              f"enforcement)", flush=True)
    json.dump(stats, open(art_path, "w"), indent=1)
    return stats
